config/routes.rb
Rails.application.routes.draw do
  get 'interactions/show'
  get 'interactions/destroy'
  get 'interactions/view'

  get 'messages/index'
  get 'messages/new'
  get 'messages/create'
  get 'conversations/index'
  get 'conversations/create'
  get 'blocks/index'
  get 'blocks/new'
  get 'blocks/create'
  get 'blocks/show'
  get 'blocks/block_user'
  get 'blocks/blocked'
  get 'blocks/destroy'

  get 'blocks/view'
  get 'topics/index'
  resources :topics

  get 'followings/index'
  get 'followings/follower'
  resources :followings

  get 'blocks/index'
  get 'blocks/blocked'
  resources :blocks

  post 'followings/new', to: 'followings#create'
  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'users/index'
  get 'users/signup'
  get 'users/view'
  get 'users/show'
  get 'users/userline'

  get 'users/follow_user'
  
  get "/upvote" => "posts#upvote"
  get "/downvote" => "posts#downvote"

  get 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'view'
      get 'userline'

      get 'follow_user'

    end
    resources :profiles do
      member do
        get 'view'
      end
    end

    resources :followings do
      member do
        get 'follow_user'
      end
    end

    resources :blocks do
      member do
        get 'block_user'
      end
    end

    resources :interactions do
      member do
        get 'view'
      end
    end

  end
  root "sessions#login"


  get 'profiles/show'
  get 'profiles/view'

  # root 'profiles#show'

  resources :conversations do
    resources :messages
  end

  get 'posts/index'
  get 'posts/show'
  get 'posts/view'
  get 'posts/userline'


  get 'followings/index'
  get 'followings/show'


  resources :posts do
    member do
      get 'view'
      get 'userline'
    end
    resources :comments
  end

  resources :followings do
    member do
      get 'follow_user'
      get 'view'

    end
    resources :comments
  end

  resources :blocks do
    member do
      get 'block_user'
      get 'view'

    end
    resources :comments
  end

  # root 'post#index'

  get 'profiles/edit'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'profiles#edit'


end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  #validates :Name, presence: true
  validates :Phone, length: { maximum: 10, minimum: 10 }, allow_blank: true, numericality: {only_integer: true}
  validates :Bio, length: { maximum: 100 }
  has_one_attached :picture, dependent: :destroy
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @profile = Profile.all
  end

  def show
    @profile = Profile.find_by(Name: current_user.username)
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to @profile
    else
      render 'new'
    end
  end

  def edit
    @profile = Profile.find(params[:user_id])
  end

  def update
    @profile = Profile.find(params[:user_id])

    if @profile.update(profile_params)
      redirect_to user_profile_path(@profile)
    else
      render 'edit'
    end
  end

  def view
    @profile = Profile.find(params[:id])
  end

  def destroy
    @profile = Profile.find(params[:user_id])
    @profile.destroy

    redirect_to @profile
  end

  private
  def profile_params

    params.require(:profile).permit(:Name, :Email, :Phone, :gender, :Bio, :picture, :privacy)

  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>
<%= form_for :profile, url: user_profile_path(@profile), method: :patch do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited
        this article from being saved:</h2>
      <ul>
        <% @profile.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :Name %><br>
    <%= @profile.Name %>
  </p>

  <p>
    <%= f.label :Email %><br>
    <%= @profile.Email %>
  </p>

  <p>
    <%= f.label :Phone %><br>
    <%= f.telephone_field :Phone %>
  </p>

  <p>
    <%= f.label :Gender %><br>
    <%= f.select :gender, %w{ Female Male Secret}, :include_blank => "Blank" %>
  <p>
  <p>
    <%= f.label :Bio %><br>
    <%= f.text_area :Bio %>
  </p>

  <%= f.label "Post picture" %>
  <%= f.file_field :picture %><br>

  <p>
    <%= f.label :Privacy %><br>
    <%= f.select :privacy, %w{ Everyone Followers None}%>
  <p>


  <p>
    <strong>Followings:</strong>
    <%= @profile.user.followings.length %>
  </p>

  <p>
    <strong>Followers:</strong>
    <%= Following.where(:name => @profile.Name, :category => "User").count %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', user_profile_path(@profile) %>

app/views/profiles/index.html.erb
<h1>Profile</h1>
<%= link_to 'Create your profile :)', new_profile_path %>

app/views/profiles/new.html.erb
<h1>Profile</h1>
<%= form_for :profile, url: profiles_path do |f|%>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited
        this article from being saved:</h2>
      <ul>
        <% @profile.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
  </p>

  <p>
    <%= f.label :Email %><br>
    <%= f.email_field :Email %>
  </p>

  <p>
    <%= f.label :Phone %><br>
    <%= f.telephone_field :Phone %>
  </p>

  <p>
    <%= f.label :Bio %><br>
    <%= f.text_area :Bio %>
  </p>

  <%= f.label "Post picture" %>
  <%= f.file_field :picture %><br>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/profiles/show.html.erb
<h1>Profile</h1>
<p>
  <strong>Name:</strong>
  <%= @profile.Name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @profile.Email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @profile.Phone %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @profile.gender %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @profile.Bio %>
</p>

<% if @profile.picture.attached? %>
  <img src="<%=(url_for(@profile.picture))%>"
  height="200">
<% end %>

<p>
  <strong><%= link_to "Followings", followings_index_path%>:</strong>
  <%= @profile.user.followings.length %>
</p>

<p>
  <strong><%= link_to "Followers", followings_follower_path(@profile.user)%>:</strong>
  <%= Following.where(:name => @profile.Name, :category => "User").count %>
</p>

<br><br>
<% @user = User.find_by(username: current_user.username) %>
<%= link_to 'My interactions', interactions_show_path %>

<br>
<%= link_to 'Edit', edit_user_profile_path(@profile) %>
<%= link_to 'Back', '/welcome' %>
<br>

app/views/profiles/view.html.erb
<% @user = User.find_by(:username => @profile.Name) %>
<% if @user.id != current_user.id and Block.exists?(:user_id => @user.id, :name => current_user.username, :category => "User") %>
  <h3>Sorry, seems that you have been blocked by this user, try to be nice!</h3>
  <form>
    <input type="button" value="Go Back" onclick="history.go(-1)">
  </form>
<% else %>


  <%@followings = current_user.followings %>
  <%@temp = 0%>


<p>
  <% if @profile.picture.attached? %>
    <img src="<%=(url_for(@profile.picture))%>"
    height="200">
  <% end %>
</p>


  <% for j in 0..@followings.length - 1%>
    <%if @followings[j].name == @user.username%>
      <% @temp = 1 %>
    <%end %>
  <%end %>


<% if @profile.privacy != "None" %>

    <% if @profile.privacy == "Everyone" or @profile.privacy == nil  or ( @profile.privacy == "Followers" and @temp == 1) %>
  <h1><%= @profile.Name %>'s Profile</h1>
  <p>
    <strong>Name:</strong>
    <%= @profile.Name %>
  </p>

      <p>
        <strong>Gender:</strong>
        <%= @profile.gender %>
      </p>

      <p>
        <strong>Bio:</strong>
        <%= @profile.Bio %>
      </p>
      <p>
        <strong>Followings:</strong>
        <%= @profile.user.followings.length %>
      </p>

      <p>
        <strong>Followers:</strong>
        <%= Following.where(:name => @profile.Name, :category => "User").count %>
      </p>
    <%else%>
    <p>You donnot have the permission to see this user's profile</p>
      <%end %>
  <%else%>
    <p>You donnot have the permission to see this user's profile</p>
<%end %>


  <% @user = User.find_by(:username => @profile.Name) %>

  <% if @user.id != current_user.id and !Following.exists?(:user_id => current_user.id, :name => @user.username, :category => "User") %>
    <% if @user.id != current_user.id and !Block.exists?(:user_id => current_user.id, :name => @user.username, :category => "User") %>
      <%= link_to 'Follow', follow_user_user_following_path(:name => @profile.Name, :category => "User") %>
    <% end %>
  <% end %>
  <% if @user.id != current_user.id and !Block.exists?(:user_id => current_user.id, :name => @user.username, :category => "User") %>
    |
    <%= link_to 'Block', block_user_user_block_path(:name => @profile.Name, :category => "User") %>
  <% end %>
  <br>
  <%= link_to 'Userline', userline_user_path(@profile.user) %> |
  <%= link_to 'Interactions', view_user_interaction_path(@profile.user) %> |
  <%= link_to 'Followings', view_following_path(@profile.user) %>
  <br>
  <%= link_to "Send Message", conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: "post" %> |
  <%= link_to 'Back to Topic', topics_path %>
<% end %>