config/routes.rb
Rails.application.routes.draw do
  get 'interactions/show'
  get 'interactions/destroy'
  get 'interactions/view'

  get 'messages/index'
  get 'messages/new'
  get 'messages/create'
  get 'conversations/index'
  get 'conversations/create'
  get 'blocks/index'
  get 'blocks/new'
  get 'blocks/create'
  get 'blocks/show'
  get 'blocks/block_user'
  get 'blocks/blocked'
  get 'blocks/destroy'

  get 'blocks/view'
  get 'topics/index'
  resources :topics

  get 'followings/index'
  get 'followings/follower'
  resources :followings

  get 'blocks/index'
  get 'blocks/blocked'
  resources :blocks

  post 'followings/new', to: 'followings#create'
  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'users/index'
  get 'users/signup'
  get 'users/view'
  get 'users/show'
  get 'users/userline'

  get 'users/follow_user'
  
  get "/upvote" => "posts#upvote"
  get "/downvote" => "posts#downvote"

  get 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'view'
      get 'userline'

      get 'follow_user'

    end
    resources :profiles do
      member do
        get 'view'
      end
    end

    resources :followings do
      member do
        get 'follow_user'
      end
    end

    resources :blocks do
      member do
        get 'block_user'
      end
    end

    resources :interactions do
      member do
        get 'view'
      end
    end

  end
  root "sessions#login"


  get 'profiles/show'
  get 'profiles/view'

  # root 'profiles#show'

  resources :conversations do
    resources :messages
  end

  get 'posts/index'
  get 'posts/show'
  get 'posts/view'
  get 'posts/userline'


  get 'followings/index'
  get 'followings/show'


  resources :posts do
    member do
      get 'view'
      get 'userline'
    end
    resources :comments
  end

  resources :followings do
    member do
      get 'follow_user'
      get 'view'

    end
    resources :comments
  end

  resources :blocks do
    member do
      get 'block_user'
      get 'view'

    end
    resources :comments
  end

  # root 'post#index'

  get 'profiles/edit'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'profiles#edit'


end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts
  validates :title, presence: true,
           length: { maximum: 20}
  validates :description, presence: true,
           length: {maximum: 140}

  scope :title, -> {}
end



#def aug
#  Post.find_by_sql("SELECT posts.title FROM posts INNER JOIN topics ON posts.topic = topics.title")
#end

#def fuc
#  Post.find_by_sql("SELECT topics.title FROM posts, topics WHERE posts.topic = topics.title")
#  Post.distinct.pluck(:title)
#end

#def fuc2
#  Post.find_by_sql("SELECT posts.text FROM posts INNER JOIN topics ON posts.topic = topics.title")
#  Post.distinct.pluck(:desc)
#end
#Topic.find_by_sql"SELECT topic FROM posts, topics WHERE posts.topic = topics.title"

#<% fuc.each do |fuc| %>
#  <tr>
#<th>
#    <%= fuc %> <br>
#    </th>
#  </tr>
#<% end %>

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  helper_method :sort_column, :sort_direction
  def index

    @topics = Topic.order(sort_column + ' ' + sort_direction)
    #@topics = Topic.all
  end

  def sort_column
    Topic.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end


  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      redirect_to @topic
    else
      render 'new'
    end
  end

  def update
    @topic = Topic.find(params[:id])

    if @topic.update(topic_params)
      redirect_to @topic
    else
      render 'edit'
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @post = Post.where(:topic => @topic.title)
    for i in 0..Post.where(:topic => @topic.title).length - 1
      @post[i].destroy
    end

    @block = Block.where(:name => @topic.title, :category => "Topic")
    @block.each { |blocks|
      blocks.destroy
    }

    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_path
  end

  private
  def topic_params
    params.require(:topic).permit(:title, :description)
  end


end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for @topic do |form| %>

  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@topic.errors.count, "error") %> prohibited
        this topic from being saved:
      </h2>
      <ul>
        <% @topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :Description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>


<% end %>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing Topics</h1>


<table>
  <% if @topics[0] != nil %>
    <tr>
      <th><%= sortable "title" %></th>
      <th><%= sortable "description" %></th>
      <th><%= sortable "Count" %></th>
      <th><%= sortable "updated_at" %></th>
      <th></th>
    </tr>
  <% else %>
    <h4>Empty Topics! Create One Through Post Or Below!</h4>
  <% end %>
  <% @topics.each do |topic| %>
    <tr>

      <% if Post.where(:topic => topic.title).length != 0 and !Block.exists?(:user_id => current_user.id, :name => topic.title, :category => "Topic")%>


        <td><%= topic.title %></td>
        <td><%= topic.description %></td>
        <td><%= Post.where(:topic => topic.title).length %></td>
        <td><%= Post.where(:topic => topic.title).pluck(:created_at).last %></td>
        <td><%= link_to 'Show', topic_path(topic) %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>

        <td><%= link_to 'Destroy', topic_path(topic),
                        method: :delete,
                        data: {confirm: 'Are you sure?'} %></td>

      <% end %>
    </tr>
  <% end %>
  <%= link_to "Create Topic", new_topic_path %>


</table>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p>
  <strong>Topic Name:</strong> <br>
  <%= @topic.title %>
</p>

<p>
  <strong>Topic Description:</strong> <br>
  <%= @topic.description %>
</p>

<p>
  <strong>Topic Post:</strong> <br>

</p>



<table>
  <tr>
  <th>Title</th>
  <th>Text</th>
    <th>Likes</th>
  </tr>

  <%@post = Post.where(:topic => @topic.title)%>
  <% @post.sort_by { | pvote | pvote.get_upvotes.size }.reverse.each do |post|%>

    <% @user = User.find_by(username: post.author) %>
    <%@followings = current_user.followings %>
    <%@temp = 0%>

    <% for j in 0..@followings.length - 1%>
      <%if @followings[j].name == @user.username%>
      <% @temp = 1 %>
      <%end %>
    <%end %>

    <% unless Block.exists?(:user_id => @user.id, :name => current_user.username, :category => "User") or Block.exists?(:user_id => current_user.id, :name => post.author, :category => "User")%>
      <% if post.privacy != "None" %>
      <% if @user.id == current_user.id or post.privacy == "Everyone" or post.privacy == nil or (post.privacy == "Follower Only" and @temp == 1)%>
      <tr>
        <td> <%= post.title %></td>
        <td> <%= post.text %></td>
        <td> <%= post.get_upvotes.size %></td>
        <td> <%= link_to 'Check', post_path(post) %> </td>
      </tr>
        <% else %>
          <tr>
      <td> You don't have the permission to view this post</td>
          </tr>
      <% end %>
      <% else %>
        <tr>
        <td> You don't have the permission to view this post</td>
        </tr>
      <% end %>
    <% end %>

    <br/>
  <% end %>

  </table>

<p></p>
<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>
<% unless Following.exists?(:user_id => current_user.id, :name => @topic.title, :category => "Topic") %>
  <% unless Block.exists?(:user_id => current_user.id, :name => @topic.title, :category => "Topic") %>
    |
    <%=  link_to 'Follow', follow_user_following_path(:name => @topic.title, :category => "Topic") %>
  <% end %>
<% end %>
<% unless Block.exists?(:user_id => current_user.id, :name => @topic.title, :category => "Topic")%>
  |
  <%= link_to 'Block', block_user_block_path(:name => @topic.title, :category => "Topic") %>
<% end %>