config/routes.rb
Rails.application.routes.draw do
  get 'interactions/show'
  get 'interactions/destroy'
  get 'interactions/view'

  get 'messages/index'
  get 'messages/new'
  get 'messages/create'
  get 'conversations/index'
  get 'conversations/create'
  get 'blocks/index'
  get 'blocks/new'
  get 'blocks/create'
  get 'blocks/show'
  get 'blocks/block_user'
  get 'blocks/blocked'
  get 'blocks/destroy'

  get 'blocks/view'
  get 'topics/index'
  resources :topics

  get 'followings/index'
  get 'followings/follower'
  resources :followings

  get 'blocks/index'
  get 'blocks/blocked'
  resources :blocks

  post 'followings/new', to: 'followings#create'
  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'users/index'
  get 'users/signup'
  get 'users/view'
  get 'users/show'
  get 'users/userline'

  get 'users/follow_user'
  
  get "/upvote" => "posts#upvote"
  get "/downvote" => "posts#downvote"

  get 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'view'
      get 'userline'

      get 'follow_user'

    end
    resources :profiles do
      member do
        get 'view'
      end
    end

    resources :followings do
      member do
        get 'follow_user'
      end
    end

    resources :blocks do
      member do
        get 'block_user'
      end
    end

    resources :interactions do
      member do
        get 'view'
      end
    end

  end
  root "sessions#login"


  get 'profiles/show'
  get 'profiles/view'

  # root 'profiles#show'

  resources :conversations do
    resources :messages
  end

  get 'posts/index'
  get 'posts/show'
  get 'posts/view'
  get 'posts/userline'


  get 'followings/index'
  get 'followings/show'


  resources :posts do
    member do
      get 'view'
      get 'userline'
    end
    resources :comments
  end

  resources :followings do
    member do
      get 'follow_user'
      get 'view'

    end
    resources :comments
  end

  resources :blocks do
    member do
      get 'block_user'
      get 'view'

    end
    resources :comments
  end

  # root 'post#index'

  get 'profiles/edit'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'profiles#edit'


end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :user

  has_many :comments, dependent: :destroy
  validates :topic, presence: { message: "topic cannot be empty" },
            length: {maximum: 100}
  validates :title, presence: { message: "title cannot be empty" },
            length: {maximum: 100}
  validates :text, presence: { message: "text cannot be empty" },
            length: {maximum: 200}
  #attr_accessor :anonymous
  #validates :vote
  has_one_attached :picture, dependent: :destroy

end


#def aug
#  Post.find_by_sql("SELECT posts.title FROM posts INNER JOIN topics ON posts.topic = topics.title")
#end

#def fuc1
  # Post.find_by_sql("SELECT posts.title FROM posts INNER JOIN topics ON posts.topic = topics.title")
  # # Post.distinct.pluck(:topic)
#end

#def fuc2
# Post.find_by_sql("SELECT posts.text FROM posts INNER JOIN topics ON posts.topic = topics.title")
# Post.distinct.pluck(:text)
#end

#<p>
#<%= Post.find_by_sql("SELECT posts.topic FROM posts INNER JOIN topics ON posts.topic = topics.title") %>
#</p>

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :show, :destroy]
  def new
    @post = Post.new
  end

  def create
    @user = User.find_by(username: current_user.username)
    @post = @user.posts.new(post_params)
    @post.author = @user.username
    if params[:anonymous]
      @post.anonymous = "1"
    else
      @post.anonymous = "0"
    end

    if @post.save


      if Topic.exists?(title: @post.topic)
        # No Topic Needed
      else
        topic = Topic.new
        topic.title = @post.topic
        topic.description = "default"
        topic.save!
        flash[:notice] = topic
      end

      
      flash[:notice] = "Post was successfully created"
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
    @post.picture.attach(params[:picture])
  end

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build
  end

  def index
    @post = Post.all.order(:updated_at).reverse_order
  end

  def userline
    @user = User.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    @topic = Topic.where(:title => @post.topic)
    if Post.where(:topic => @topic[0].title).length == 1
      @topic[0].destroy
    end

    if @post.update(post_params)
      if Topic.exists?(title: @post.topic)
      else
        topic = Topic.new
        topic.title = @post.topic
        topic.description = "default"
        topic.save!
        flash[:notice] = topic
      end
      flash[:notice] = "Post was updated"
      redirect_to @post
    else
      flash[:notice] = "Post was not updated"
      render 'edit'
    end
  end


  def destroy
    # Destroy TBD
    #
    #
    #
    #@user = User.find(params[:user_id])
    #@post = @user.posts.find(params[:id]

    @post = Post.find(params[:id])

    @topic = Topic.where(:title => @post.topic)

    @post.destroy

    if Post.where(:topic => @topic[0].title).length == 0
      @topic[0].destroy
    end

    @interaction = Interaction.where(:postID => @post.id)
    @interaction.each { |interactions|
      interactions.destroy
    }

    flash[:notice] = "Post was deleted"
    redirect_to posts_path
  end
  
  def upvote
    @post = Post.find(params[:id])
    if current_user.up_votes @post
      @post.liked_by current_user
    end
    @user = User.find_by(username: current_user.username)
    if Interaction.find_by(postID: @post.id).nil?
      @interaction = @user.interactions.create(:postID => @post.id, :category => "Upvote")
    else
      @interaction = Interaction.find_by(postID: @post.id)
      if @interaction.category == "Downvote"
        @interaction.destroy
        @interaction = @user.interactions.create(:postID => @post.id, :category => "Upvote")
      end
    end

    redirect_to @post
  end

  def downvote
    @post = Post.find(params[:id])
    if current_user.down_votes @post
      @post.downvote_by current_user
    end
    @user = User.find_by(username: current_user.username)
    if Interaction.find_by(postID: @post.id).nil?
      @interaction = @user.interactions.create(:postID => @post.id, :category => "Downvote")
    else
      @interaction = Interaction.find_by(postID: @post.id)
      if @interaction.category == "Upvote"
        @interaction.destroy
        @interaction = @user.interactions.create(:postID => @post.id, :category => "Downvote")
      end
    end
    redirect_to @post
  end

  private
  def picture=(picture_field)
    transaction do
      if picture_field.size>0 then
        @picture_size=picture_field.size
        @picture_type=picture_field.content_type.chomp
        self.picture_content_type =@picture_type
        self.picture_data = picture_field.read
      end
    end
  end
  def post_params

    params.require(:post).permit(:topic, :title, :text, :anonymous, :picture, :privacy)

  end
  
  def set_post
    @post = Post.find(params[:id])
  end
  
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :topic %><br>
    <%= f.text_field :topic %>
  </p>


  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <dl class="form anonymous">
    <%= check_box_tag :anonymous, 1, params[:anonymous] %>
    <%= label_tag "Anonymous" %>
  </dl>

  <!-- <tr>
  <td width="15%"><b>image</b></td>
  <td><%= file_field 'post', 'picture' %></td>
  </tr> -->

<%= f.label "Post picture" %>
<%= f.file_field :picture %><br>

  <p>
    <b>Privacy( Who can view my Post? )</b><br />
      <%= f.radio_button :privacy, 'Everyone' %>
      <%= f.label :privacy, 'Everyone', :value => 'every' %>
      <%= f.radio_button :privacy, 'None' %>
      <%= f.label :privacy, 'None', :value => 'none' %>
      <%= f.radio_button :privacy, 'Follower Only' %>
      <%= f.label :privacy, 'Follower Only', :value => 'follow' %>
  </p>

  <p>
    <%= f.submit %>
  </p>



<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>User Posts</h1>
<%= link_to 'Back to topic', topics_path %><br><br><br><br><br>
<%= link_to 'Make a post', new_post_path %>

<table>
  <% if @post[0] != nil %>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Posted at</th>
    <th>User</th>
    <th>Likes</th>
  </tr>
  <% end %>

  <% @post.each do |post| %>
    <% @user = User.find_by(username: current_user.username) %>
    <% if @user.username == post.author %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.text %></td>
        <td><%= post.created_at %>
        <% if post.anonymous == 1 %>
        <td>Anonymous
          <% else %>
          <td><%= post.author %>
          <% end %>
        <td><%= post.get_upvotes.size %></td>
        <td><%= link_to 'Show', post_path(post) %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post_path(post),
                      method: :delete,
                      data: { confirm: 'Are you sure about that?' } %></td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% @user = User.find_by(:username => @post.author) %>
<% if @user.id != current_user.id and Block.exists?(:user_id => @user.id, :name => current_user.username, :category => "User") %>
  <h3>Sorry, seems that you have been blocked by this user, try to be nice!</h3>
  <form>
    <input type="button" value="Go Back" onclick="history.go(-1)">
  </form>
<% else %>

  <% @temp = Topic.where(:title => @post.topic) %>
    <p>
      <strong>Topic:</strong>
      <%= link_to @post.topic, topic_path(@temp.pluck(:id)[0]) %>
    </p>
    <p>
      <strong>Title:</strong>
      <%= @post.title %>
    </p>

    <p>
      <strong>Text:</strong>
      <%= raw Rinku.auto_link(@post.text, mode = :all) %>
    </p>

    <p>
      <strong>Privacy:</strong>
      <%= @post.privacy %>
      <%if @post.privacy == nil %>
      <%="Everyone"%>
      <%end %>
    </p>

  <% end %>

  <p>
    <strong>Posted by:</strong>

    <% if @post.anonymous == 1 %>
    <td>Anonymous</td>
  <% else @user = User.find_by(username: @post.author)%>
    <% if @post.author == current_user.username %>
      <td>Yourself</td>
    <% else %>
      <%= link_to @user.username, view_user_path(@user) %>
    <% end %>
  </p>

  <p>
    Likes: <%= @post.get_upvotes.size %>
    Dislikes: <%= @post.get_downvotes.size %>
    <%= link_to 'UpVote', upvote_path(:id => @post.id) %>
    <%= link_to 'DownVote', downvote_path(:id => @post.id) %>
  </p>


  <% if @post.picture.attached? %>
    <img src="<%=(url_for(@post.picture))%>"
    height="500"
    alt="can not found image">
  <% end %>

  <h2>Comments</h2>
  <% @post.comments.each do |comment| %>
    <% if comment.commenter != nil && comment.body != nil %>
      <p>
        <strong>Commenter:</strong>
        <%= comment.commenter %>
      </p>
      <p>
        <strong>Comment:</strong>
        <%= comment.body %>
      </p>
    <% end %>
  <% end %>

  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>


  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>

<% end %>

app/views/posts/userline.html.erb
<h1><%= @user.username %>'s Userline</h1>
<% @post = @user.posts.all.order(:updated_at).reverse_order %>
<table>
  <% if @post[0] != nil %>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th>Posted at</th>
      <th>User</th>
    </tr>
  <% else %>
    <th> The user doesn't create any post.</th>
  <% end %>

  <% @post.each do |post| %>
    <% if @user.username == post.author && post.anonymous != 1 %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.text %></td>
        <td><%= post.created_at %>
        <td><%= post.author %>

        <td><%= link_to 'Show', post_path(post) %></td>
      </tr>
    <% end %>
  <% end %>
</table>
<%= link_to 'Back', view_user_path(@user) %>