config/routes.rb
Rails.application.routes.draw do
  get 'interactions/show'
  get 'interactions/destroy'
  get 'interactions/view'

  get 'messages/index'
  get 'messages/new'
  get 'messages/create'
  get 'conversations/index'
  get 'conversations/create'
  get 'blocks/index'
  get 'blocks/new'
  get 'blocks/create'
  get 'blocks/show'
  get 'blocks/block_user'
  get 'blocks/blocked'
  get 'blocks/destroy'

  get 'blocks/view'
  get 'topics/index'
  resources :topics

  get 'followings/index'
  get 'followings/follower'
  resources :followings

  get 'blocks/index'
  get 'blocks/blocked'
  resources :blocks

  post 'followings/new', to: 'followings#create'
  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'users/index'
  get 'users/signup'
  get 'users/view'
  get 'users/show'
  get 'users/userline'

  get 'users/follow_user'
  
  get "/upvote" => "posts#upvote"
  get "/downvote" => "posts#downvote"

  get 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'view'
      get 'userline'

      get 'follow_user'

    end
    resources :profiles do
      member do
        get 'view'
      end
    end

    resources :followings do
      member do
        get 'follow_user'
      end
    end

    resources :blocks do
      member do
        get 'block_user'
      end
    end

    resources :interactions do
      member do
        get 'view'
      end
    end

  end
  root "sessions#login"


  get 'profiles/show'
  get 'profiles/view'

  # root 'profiles#show'

  resources :conversations do
    resources :messages
  end

  get 'posts/index'
  get 'posts/show'
  get 'posts/view'
  get 'posts/userline'


  get 'followings/index'
  get 'followings/show'


  resources :posts do
    member do
      get 'view'
      get 'userline'
    end
    resources :comments
  end

  resources :followings do
    member do
      get 'follow_user'
      get 'view'

    end
    resources :comments
  end

  resources :blocks do
    member do
      get 'block_user'
      get 'view'

    end
    resources :comments
  end

  # root 'post#index'

  get 'profiles/edit'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'profiles#edit'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
class Block < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  attr_accessor :commenter
  validates :body, presence: { message: "text cannot be empty" },
            length: {maximum: 200}
  belongs_to :post
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: "User"
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: "User"
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :scope => :recipient_id
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)" , sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :user
end

app/models/interaction.rb
class Interaction < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id
  validates :body, length: { maximum: 200 }
  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :user

  has_many :comments, dependent: :destroy
  validates :topic, presence: { message: "topic cannot be empty" },
            length: {maximum: 100}
  validates :title, presence: { message: "title cannot be empty" },
            length: {maximum: 100}
  validates :text, presence: { message: "text cannot be empty" },
            length: {maximum: 200}
  #attr_accessor :anonymous
  #validates :vote
  has_one_attached :picture, dependent: :destroy

end


#def aug
#  Post.find_by_sql("SELECT posts.title FROM posts INNER JOIN topics ON posts.topic = topics.title")
#end

#def fuc1
  # Post.find_by_sql("SELECT posts.title FROM posts INNER JOIN topics ON posts.topic = topics.title")
  # # Post.distinct.pluck(:topic)
#end

#def fuc2
# Post.find_by_sql("SELECT posts.text FROM posts INNER JOIN topics ON posts.topic = topics.title")
# Post.distinct.pluck(:text)
#end

#<p>
#<%= Post.find_by_sql("SELECT posts.topic FROM posts INNER JOIN topics ON posts.topic = topics.title") %>
#</p>

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  #validates :Name, presence: true
  validates :Phone, length: { maximum: 10, minimum: 10 }, allow_blank: true, numericality: {only_integer: true}
  validates :Bio, length: { maximum: 100 }
  has_one_attached :picture, dependent: :destroy
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts
  validates :title, presence: true,
           length: { maximum: 20}
  validates :description, presence: true,
           length: {maximum: 140}

  scope :title, -> {}
end



#def aug
#  Post.find_by_sql("SELECT posts.title FROM posts INNER JOIN topics ON posts.topic = topics.title")
#end

#def fuc
#  Post.find_by_sql("SELECT topics.title FROM posts, topics WHERE posts.topic = topics.title")
#  Post.distinct.pluck(:title)
#end

#def fuc2
#  Post.find_by_sql("SELECT posts.text FROM posts INNER JOIN topics ON posts.topic = topics.title")
#  Post.distinct.pluck(:desc)
#end
#Topic.find_by_sql"SELECT topic FROM posts, topics WHERE posts.topic = topics.title"

#<% fuc.each do |fuc| %>
#  <tr>
#<th>
#    <%= fuc %> <br>
#    </th>
#  </tr>
#<% end %>

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end


class PasswordValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A(?=.{8,}) (?=.*[[:^alnum:]])/x
      record.errors[attribute] << (options[:message] || "Password is not valid(at least 8 char and one special char)")
    end
  end
end

class User < ApplicationRecord
  acts_as_voter
  before_create :generate_token

  def generate_token
    auth_token = nil
    begin
      auth_token = SecureRandom.urlsafe_base64
      Rails.logger.info "===auth_token==========#{auth_token}"
    end while User.exists?(auth_token:"#{auth_token}")
    self.auth_token = auth_token
  end

  has_many :posts, dependent: :destroy
  #has_many :comments, dependent: :destroy
  has_many :followings, dependent: :destroy
  has_many :blocks, dependent: :destroy
  has_many :interactions, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :conversations, :foreign_key => :sender_id, dependent: :destroy
  validates :password, presence: true, password:true
  validates :password, confirmation: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence:true, email:true, uniqueness: true
end

app/helpers/application_helper.rb
module ApplicationHelper
  #helper methods for config flash notice
  def flash_class(level)
    case level.to_sym
    when :notice then "alert alert-success"
    when :success then "alert alert-success"
    when :error then "alert alert-danger"
    when :alert then "alert alert-danger"
    when :warning then "alert alert-warning"
    end
  end
  def flash_prefix(level)
    case level.to_sym
    when :notice then "Success!"
    when :success then "Success!"
    when :error then "Error!"
    when :alert then "Alert!"
    when :warning then "Warning!"
    end
  end

  def sortable(column, title = nil)
    title ||= column.titleize
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
  end

end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/interactions_helper.rb
module InteractionsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeBlog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <style>
      ul.nav-section {


          list-style-type: none;
          margin: 0;
          padding: 0;
          overflow: hidden;
          background-color: #333;
      }


      li.nav-section {
          float: left;
      }

      li a, .dropbtn {
          display: inline-block;
          color: white;
          text-align: center;
          padding: 14px 16px;
          text-decoration: none;
      }

      li a:hover, .dropdown:hover .dropbtn {
          background-color: red;
      }

      li.dropdown {
          display: inline-block;
      }

      .dropdown-content {
          display: none;
          position: absolute;
          background-color: #f9f9f9;
          min-width: 160px;
          box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
          z-index: 1;
      }

      .dropdown-content a {
          color: black;
          padding: 12px 16px;
          text-decoration: none;
          display: block;
          text-align: left;
      }

      .dropdown-content a:hover {background-color: #f1f1f1;}

      .dropdown:hover .dropdown-content {
          display: block;
      }
  </style>
</head>

<body>
<!-- config of flash notice; displaying notice on top left of screen -->
<div id="flash-messages-section">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> no-radius fade in">
      <a href="#" data-dismiss="alert" class="close">Close</a>
      <ul>
        <li style="color: brown">
          <strong><%= flash_prefix(key)%></strong>&nbsp;<%= value %>
        </li>
      </ul>
    </div>
  <% end %>
</div>
<h1 style="text-align: center; font-family: 'ROG Fonts v1.6'; font-size: 600%"> Awesome Blog </h1>
<% if logged_in? %>
  <ul class="nav-section">
    <li class="active" style="float: right"> <%= link_to "Home", welcome_path%>  </li>
    <li class="nav-section"> <%= link_to "Profile", user_path(current_user)%> </li>
    <li class="nav-section"> <%= link_to "Topics", topics_index_path%>  </li>
    <li class="nav-section"> <%= link_to "Posts", posts_path%>  </li>
    <li class="nav-section"> <%= link_to "Followings", followings_index_path%>  </li>
    <li class="nav-section"> <%= link_to "Followers", followings_follower_path%>  </li>
    <li class="nav-section"> <%= link_to "Messages", conversations_path%>  </li>
    <li class="dropdown">
      <a href="javascript:void(0)" class="dropbtn">Account</a>
      <div class="dropdown-content">
        <%= link_to "Logout", logout_path, method: :get, data: { confirm: 'Are you sure about that?' }%>
        <%= link_to "Delete Account", user_path(current_user), method: :delete, data: { confirm: 'Are you sure?' }%>
        <%= link_to "Settings", blocks_index_path%>
      </div>
    </li>
  </ul>
<%end%>
<%= yield %>
<!-- button to manage accounts; Usage for 'Admin' user only -->
<% if logged_in? %>
  <% if current_user.username == "Admin"%>
    <%= link_to 'Manage Accounts', users_index_path %>
  <% end  %>
<% end  %>

</body>
</html>